[features]
seeds = false
skip-lint = false
[programs.localnet]
simple_vote = "7SGsTFdVygX11d3Dz3ZaBJKnr2mBaX9M8fxc4q6e5rNZ"
dedup_vote = "5Q4KkEoLHzFNGaDZzfarZ99EbgMpwQsERAyTUuYEqANi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/kyle/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
